### PR TITLE
banner for UGM

### PR DESCRIPTION
**Pull request by orbeckst**
- basic MDA banner for user group meeting
- requested in https://github.com/MDAnalysis/MDAnalysis.github.io/pull/278#discussion_r1197607901

### CODE REVIEW

**Comment by orbeckst** [comment]
@jennaswa @micaela-matta please have a look and make suggestions for changes.

**Review by micaela-matta — APPROVED** [review]
looks good - can we also have a version with all white background to make it easier for pdf fliers/other materials?

**Comment by orbeckst** [comment]
Here you go:
UGM Banner white bg

**Comment by orbeckst** [comment]
@micaela-matta @jennaswa please merge if you're happy with it, otherwise do a request changes review and tell me what you need. Thanks!

**Review by jennaswa — APPROVED** [review]

**Pull request merged**
